namespace AppForSEII2526.API.Models
{
    public class Rental
    {
        //public enum PaymentMethodTypes
        //{//Metodos de pago}
        //    Efectivo,
        //    TarjetaCredito,
        //    TarjetaDebito,
        //    TransferenciaBancaria,
        //    PagoMovil,
        //    PayPal,
        //    Criptomoneda,
        //    Cheque

        //}
        public Rental()
        {

        }

        public Rental(PaymentMethodTypes paymentMethod, DateTime rentalDate, decimal totalPrice, bool deliveryCarDealer, DateTime startdate, DateTime enddate, IList<RentalItem> rentalItems)
        {
            PaymentMethod = paymentMethod;
            RentalDate = rentalDate;
            TotalPrice = totalPrice;
            DeliveryCarDealer = deliveryCarDealer;
            RentalDateFrom = startdate;
            RentalDateTo = enddate;
            RentalItems = rentalItems;
        }

        public Rental(ApplicationUser applicationUser, DateTime rentalDate, PaymentMethodTypes paymentMethod, DateTime rentalDateFrom, DateTime rentalDateTo, IList<RentalItem> rentalItems)
        {
            TotalPrice = rentalItems.Sum(ri => ri.PriceForRenting * (rentalDateTo - rentalDateFrom).Days);

            //autogenerated
            RentalDateFrom = rentalDateFrom;
            RentalDateTo = rentalDateTo;
            RentalDate = rentalDate;
            ApplicationUser = applicationUser;
            RentalItems = rentalItems;
            PaymentMethod = paymentMethod;
        }



        [Key]
        public int Id { get; set; }

        [Display(Name = "Payment Method")]
        public PaymentMethodTypes PaymentMethod { get; set; }

        [Precision(10, 2)]
        public decimal TotalPrice { get; set; }

        public bool DeliveryCarDealer { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime RentalDateFrom { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime RentalDateTo { get; set; }

        public DateTime RentalDate { get; set; }

        public IList<RentalItem> RentalItems { get; set; }

        public ApplicationUser ApplicationUser { get; set; }
    }

}

